services:
  - type: web
    name: aiconsulthub
    env: node
    region: singapore # Using Singapore region for better performance in Asia
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aiconsulthub-db
          property: connectionString

databases:
  - name: aiconsulthub-db
    region: singapore
    plan: free
