services:
  - type: web
    name: aiconsulthub
    env: node
    region: singapore # Using Singapore region for better performance in Asia
    buildCommand: |
      npm install
      npm run build
      npm run db:push
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    plan: starter # Specify the instance size
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aiconsulthub-db
          property: connectionString
      - key: ADMIN_TOKEN
        sync: false # Will be set manually in Render dashboard
      - key: PORT
        value: "5000"
      - key: WS_ENABLED
        value: "true"
    # Add WebSocket specific configurations
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildEnv:
      - key: NODE_VERSION
        value: ~20.0.0

databases:
  - name: aiconsulthub-db
    region: singapore
    plan: starter # Using starter plan for development
    ipAllowList: [] # Only allow internal connections