services:
  - type: web
    name: aiconsulthub
    env: node
    region: singapore # Using Singapore region for better performance in Asia
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    plan: starter # Specify the instance size
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aiconsulthub-db
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_TOKEN
        sync: false
    buildEnv:
      - key: NODE_VERSION
        value: ~20.0.0

databases:
  - name: aiconsulthub-db
    region: singapore
    plan: starter # Using starter plan for development
    ipAllowList: [] # Only allow internal connections